Parameters:
  Environment:
    Type: String

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
      Parameters:
        Environment: !Ref Environment

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ec2.yaml
      Parameters:
        Environment: !Ref Environment

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: rds.yaml
      Parameters:
        Environment: !Ref Environment

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: s3.yaml
      Parameters:
        Environment: !Ref Environment
